name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14', '1.15' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run Go ${{ matrix.go }} Tests
        run: |
          go test ./... -cover -race
